---
# tasks file for minetest installation

- name: Install wireguard
  include: secure.yml

- name: Get minetest repo
  apt_repository:
    repo: ppa:minetestdevs/stable

- name: Install minetest
  apt:
    name: "minetest={{ lookup('env','MT_VERSION') }}"
    state: present

- name: Add group "minetest"
  group: name=minetest

- name: Add user "minetest"
  user: name=minetest group=minetest

- name: Create the configuration directory
  file:
    path: {{ lookup('env','MT_DISK') }}/mtconf
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: Copy configuration file
  template:
    src: minetest.conf
    dest: {{ lookup('env','MT_DISK') }}/mtconf
  notify: "Restart Minetest Service"

- name: Copy unit file
  template:
    src: minetest.service
    dest: /etc/systemd/system/minetest.service
    mode: 0644
  notify: "Restart Minetest Service"
