#
# confgichanges.yml - modify minetest.conf for special module needs

- name: Get the Mapserver Config
  shell: "cat {{ mthome }}/data/mapserver.json"
  register: mps_config

- name: extract secret key from mapserver config
  set_fact:
    mps_key: "{{mps_config.stdout | from_json | json_query('webapi.secretkey')}}"

- name: Add Config Line for "mapserver.key"
  lineinfile:
    path: "{{ mthome }}/conf/minetest.conf"
    regexp: "^mapserver.key"
    line: "mapserver.key = {{mps_key}}"
  notify: 
    - Restart Minetest Service
    - Restart Mapserver Service

- name: Add Config Line for "secure.http_mods"
  lineinfile:
    path: "{{ mthome }}/conf/minetest.conf"
    regexp: "^secure.http_mods"
    line: "secure.http_mods = mapserver"
  notify: 
    - Restart Minetest Service
    - Restart Mapserver Service

- name: Add Config Line for "secure.trusted_mods"
  lineinfile:
    path: "{{ mthome }}/conf/minetest.conf"
    regexp: "^secure.trusted_mods"
    line: "secure.trusted_mods = skinsdb"
  notify: 
    - Restart Minetest Service
    - Restart Mapserver Service

- name: Switch off village generation but leave the module running
  lineinfile:
    path: "{{ mthome }}/mods/mg_villages/config.lua"
    regexp: "^mg_villages.ENABLE_VILLAGES"
    line: "mg_villages.ENABLE_VILLAGES = false;"
  notify: 
    - Restart Minetest Service
    - Restart Mapserver Service

- name: Switch off house generation but leave the module running
  lineinfile:
    path: "{{ mthome }}/mods/mg_villages/config.lua"
    regexp: "^mg_villages.INVERSE_HOUSE_DENSITY"
    line: "mg_villages.INVERSE_HOUSE_DENSITY = 0;"
  notify: 
    - Restart Minetest Service
    - Restart Mapserver Service
