- name: Download "{{module}}"
  get_url: 
    url: "https://github.com/{{module_path}}/archive/master.zip"
    dest: /tmp/master.zip

- name: Unzip the Download
  unarchive:
     src: /tmp/master.zip
     dest: "{{ lookup('env','MT_DISK') }}/mods"
     owner: minetest
     group: minetest
     remote_src: true

- name: Add Config Line for "{{module}}"
  lineinfile:
    path: "{{ lookup('env','MT_DISK') }}/data/world.mt"
    regexp: "^load_mod_{{module}} ="
    line: "load_mod_{{module}} = true"
  notify: "Restart Minetest Service"
