#
# mods.yml - Define the mods that are to be loaded on your server
#            vars for each call to mods_download:
#             - module: name of module
#             - module_path: where is the source module located? this is a part of the download path
#             - load_mods: list of names that are to be supplied to world.mt file as load directive. 
#                          Can be omitted if name is equal to module name
#             - load_conf: config line for minetest.conf file
#             - src: 'github' (default), which will download from archive/master.zip
#                    or 'ContentDB', which will follow the redirect on the web site to the orginal upload zip
#             - move: if true, try to move the unzipped mod directory from <module>-master to <module>. Some mods rely on the proper name.
#
# 2020-02-21 created by selfscrum 
# 
---

- name: Create mods Directory
  file: 
    path: "{{ mthome }}/mods"
    state: directory
    owner: minetest
    group: minetest

- name: Install inventory Mod
  import_tasks: mods_download.yml
  vars:
    module: unified_inventory
    module_path: minetest-mods/unified_inventory

- name: Install areas Mod
  import_tasks: mods_download.yml
  vars:
    module: areas
    module_path: minetest-mods/areas

- name: Install Books Mod
  import_tasks: mods_download.yml
  vars:
    module: books
    module_path: everamzah/books

- name: Install display Mod
  import_tasks: mods_download.yml
  vars:
    module: display_modpack
    module_path: pyrollo/display_modpack
    load_mods:
      - font_epilepsy
      - signs_road
      - signs_api
      - steles
      - font_metro
      - ontime_clocks
      - signs
      - boards
      - display_api
      - font_api
          
- name: Install maptools Mod
  import_tasks: mods_download.yml
  vars:
    module: maptools
    module_path: Calinou/maptools

- name: Install ts_furniture Mod
  import_tasks: mods_download.yml
  vars:
    module: ts_furniture
    module_path: minetest-mods/ts_furniture

- name: Install Minetest-WorldEdit Mod
  import_tasks: mods_download.yml
  vars:
    module: Minetest-WorldEdit
    module_path: Uberi/Minetest-WorldEdit
    load_mods:
      - worldedit_shortcommands
      - worldedit_commands
      - worldedit_brush
      - worldedit
      - worldedit_gui

- name: Install airboat Mod
  import_tasks: mods_download.yml
  vars:
    module: airboat
    module_path: paramat/airboat

# - name: Install poi Mod
#   import_tasks: mods_download.yml
#   vars:
#     module: poi
#     module_path: acmgit/minetest_poi

- name: Install mesecons Mod
  import_tasks: mods_download.yml
  vars:
    module: mesecons
    module_path: minetest-mods/mesecons
    load_mods:
      - mesecons
      - mesecons_walllever
      - mesecons_torch
      - mesecons_switch
      - mesecons_receiver
      - mesecons_random
      - mesecons_solarpanel
      - mesecons_powerplant
      - mesecons_pistons
      - mesecons_noteblock
      - mesecons_mvps
      - mesecons_movestones
      - mesecons_materials
      - mesecons_lightstone
      - mesecons_microcontroller
      - mesecons_insulated
      - mesecons_pressureplates
      - mesecons_stickyblocks
      - mesecons_delayer
      - mesecons_wires
      - mesecons_detector
      - mesecons_hydroturbine
      - mesecons_luacontroller
      - mesecons_alias
      - mesecons_lamp
      - mesecons_blinkyplant
      - mesecons_commandblock
      - mesecons_button
      - mesecons_doors
      - mesecons_extrawires
      - mesecons_fpga
      - mesecons_gates

# digilines base package with lines, lcd etc.
- name: Install digilines Mod
  import_tasks: mods_download.yml
  vars:
    module: digilines
    module_path: minetest-mods/digilines
    load_mods:
      - digilines

# Terminals and keyboard
- name: Install digiterms Mod
  import_tasks: mods_download.yml
  vars:
    module: digiterms
    module_path: pyrollo/digiterms
    move: true
    load_mods:
      - digiterms

# copy and paste areas
- name: Install edit Mod
  import_tasks: mods_download.yml
  vars:
    module: edit
    module_path: selfscrum/edit
    load_mods:
      - edit
    move: true

- name: Install moreblocks Mod
  import_tasks: mods_download.yml
  vars:
    module: moreblocks
    module_path: minetest-mods/moreblocks

- name: Install pkarcs Mod
  import_tasks: mods_download.yml
  vars:
    module: pkarcs
    module_path: TumeniNodes/pkarcs
    load_mods:
      - pkarcs
      - pkarcs_doors
      - pkarcs_doors3

- name: Install nether Mod
  import_tasks: mods_download.yml
  vars:
    module: nether
    module_path: minetest-mods/nether

- name: Install skinsdb Mod
  import_tasks: mods_download.yml
  vars:
    module: skinsdb
    module_path: minetest-mods/skinsdb
    load_mods:
      - skinsdb
    load_conf:
      - secure.trusted_mods = skinsdb
    move: true

- name: Install edutest-chatcommands Mod
  import_tasks: mods_download.yml
  vars:
    module: edutest-chatcommands
    module_path: zeuner/edutest-chatcommands
    load_mods:
      - edutest_chatcommands

# 2 mods for edutest belong together
- name: Install edutest Mod
  import_tasks: mods_download.yml
  vars:
    module: edutest
    module_path: zeuner/edutest

# 3 mods for cottages belong together
- name: Install handle_schematics Mod
  import_tasks: mods_download.yml
  vars:
    module: handle_schematics
    module_path: Sokomine/handle_schematics
    load_mods:
      - handle_schematics
    move: true

- name: Install cottages Mod
  import_tasks: mods_download.yml
  vars:
    module: cottages
    module_path: Sokomine/cottages
    load_mods:
      - cottages
    move: true

- name: Install mg_villages Mod
  import_tasks: mods_download.yml
  vars:
    module: mg_villages
    module_path: Sokomine/mg_villages
    load_mods:
      - mg_villages
    move: true

- name: Install mapserver Mod
  import_tasks: mods_download.yml
  vars:
    module: mapserver
    module_path: minetest-mapserver/mapserver_mod
    load_mods:
      - mapserver
    move: true

- name: Install signs_lib Mod
  import_tasks: mods_download.yml
  vars:
    module: signs_lib
    module_path: mk-pmb/minetest-mod-signs_lib

- name: Install protect Mod
  import_tasks: mods_download.yml
  vars:
    module: protect
    module_path: Zeg9/minetest-protect
    load_mods:
      - protector

- name: Install climate API Mod
  import_tasks: mods_download.yml
  vars:
    module: climate_api
    module_path: t-affeldt/climate_api
    load_mods:
      - climate_api
    move: true

- name: Install regional_weather Mod
  import_tasks: mods_download.yml
  vars:
    module: regional_weather
    module_path: t-affeldt/regional_weather
    load_mods:
      - regional_weather
    move: true

- name: Install minetest_moon_phase Mod
  import_tasks: mods_download.yml
  vars:
    module: minetest_moon_phase
    module_path: t-affeldt/minetest_moon_phase
    load_mods:
      - minetest_moon_phases
    move: true

- name: Install lightning Mod
  import_tasks: mods_download.yml
  vars:
    module: lightning
    module_path: minetest-mods/lightning
    load_mods:
      - lightning
    move: true
   
- name: Install teaching Mod
  import_tasks: mods_download.yml
  vars:
    module: teaching
    module_path: sfan5/teaching
    load_mods:
      - teaching
    src: ContentDB
    move: true

- name: Install farming Mod
  import_tasks: mods_download.yml
  vars:
    module: farming
    module_path: TenPlus1/farming
    src: ContentDB

- name: Install mobs Mod
  import_tasks: mods_download.yml
  vars:
    module: mobs
    module_path: TenPlus1/mobs
    src: ContentDB

- name: Install mobs_npc Mod
  import_tasks: mods_download.yml
  vars:
    module: mobs_npc
    module_path: TenPlus1/mobs_npc
    src: ContentDB

- name: Install mobs_animal Mod
  import_tasks: mods_download.yml
  vars:
    module: mobs_animal
    module_path: TenPlus1/mobs_animal
    src: ContentDB

- name: Install basic_materials Mod
  import_tasks: mods_download.yml
  vars:
    module: basic_materials
    module_path: VanessaE/basic_materials
    load_mods:
      - basic_materials
    move: true
    src: ContentDB

- name: Install pipeworks Mod
  import_tasks: mods_download.yml
  vars:
    module: pipeworks
    module_path: VanessaE/pipeworks
    load_mods:
      - pipeworks
    move: true
    src: ContentDB

- name: Install technic Mod
  import_tasks: mods_download.yml
  vars:
    module: technic
    module_path: RealBadAngel/technic
    load_mods:
      - technic
      - wrench
      - technic_worldgen
      - technic_cnc
      - extranodes
      - technic_chests
      - concrete
    move: true
    src: ContentDB

