- name: Download "{{module}}" from github
  get_url: 
    url: "https://github.com/{{module_path}}/archive/master.zip"
    dest: /tmp/master.zip
  when: src|default('github') == 'github'

- name: Download "{{module}}" from ContentDB
  uri: 
    url: "https://content.minetest.net/packages/{{module_path}}/download"
    dest: /tmp/master.zip
    status_code: 200,300
  when: src|default('github') == 'ContentDB'

- name: Unzip the Download
  unarchive:
     src: /tmp/master.zip
     dest: "{{ lookup('env','MT_DISK') }}/mods"
     owner: minetest
     group: minetest
     remote_src: true

- name: Add Config Line for "{{module}}" in world.mt
  lineinfile:
    path: "{{ lookup('env','MT_DISK') }}/data/world.mt"
    regexp: "^load_mod_{{item}} ="
    line: "load_mod_{{item}} = true"
  loop: "{{ load_mods | default( [ module ] ) }}"
  notify: "Restart Minetest Service"

- name: Add Config Line for "{{module}}" in minetest.conf
  lineinfile:
    path: "{{ lookup('env','MT_DISK') }}/conf/minetest.conf"
    regexp: "^{{item}}"
    line: "{{item}}"
  loop: "{{load_conf | default([])}}"
  notify: "Restart Minetest Service"
