#
# mods_download.yml - Load a minetest mod from the internet and place it correctly into the minetest installation
#
# 2020-02-21 created by selfscrum 
# 
---

- name: Download "{{module}}" from github
  get_url: 
    url: "https://github.com/{{module_path}}/archive/master.zip"
    dest: /tmp/master.zip
  when: src|default('github') == 'github'

- name: Download "{{module}}" from ContentDB
  block:
    - name: Get file location from ContentDB
      uri: 
        url: "https://content.minetest.net/packages/{{module_path}}/download"
        dest: /tmp/master.zip
        status_code: 300
      register: uri_asset

    - name: Donwload redirected file
      get_url: 
        url: "{{ uri_asset.location }}"
        dest: /tmp/master.zip
  when: src|default('github') == 'ContentDB'

- name: Unzip the Download
  unarchive:
    src: /tmp/master.zip
    dest: "{{mthome}}/mods"
    owner: minetest
    group: minetest
    remote_src: true
  when: not (move|default(false))

- name: Unzip and move the mod
  shell: "{{mthome}}/bin/movemod.sh /tmp/master.zip {{mthome}}/mods/{{load_mods[0]}}"
  when: move|default(false) == true

- name: Add Config Line for "{{module}}" in world.mt
  lineinfile:
    path: "{{mthome}}/data/world.mt"
    regexp: "^load_mod_{{item}} ="
    line: "load_mod_{{item}} = true"
  loop: "{{ load_mods | default( [ module ] ) }}"
  notify: "Restart Minetest Service"

- name: Add Config Line for "{{module}}" in minetest.conf
  lineinfile:
    path: "{{mthome}}/conf/minetest.conf"
    regexp: "^{{item}}"
    line: "{{item}}"
  loop: "{{load_conf | default([])}}"
  notify: "Restart Minetest Service"
