#
# texture.yml - Define the texture that is to be loaded on your server
#
# 2020-02-21 created by selfscrum 
# 
---
- name: Select the texture package
  set_fact: 
    texture: 'drummyfish/drummyfish'

- name: Create textures Directory
  become: yes
  file: 
    path: "{{ lookup('env','MT_DISK') }}/textures/downloads"
    state: directory
    owner: minetest
    group: minetest

- name: Download Texture path from ContentDB
  uri: 
    url: "https://content.minetest.net/packages/{{texture}}/download"
    dest: /tmp/redirect
    status_code: 300
  register: texture_asset

- name: Download redirected file
  get_url: 
    url: "{{ texture_asset.location }}"
    dest: "{{ lookup('env','MT_DISK') }}/textures/downloads/texture.zip"

- name: Unzip the Download
  unarchive:
    src: "{{ lookup('env','MT_DISK') }}/textures/downloads/texture.zip"
    dest: "{{ lookup('env','MT_DISK') }}/textures/downloads"
    owner: minetest
    group: minetest
    remote_src: true

- name: Get the Package Directory Name
  find: 
    path: "{{ lookup('env','MT_DISK') }}/textures/downloads"
    file_type: directory
  register: texture_dir

- name: Create server Directory
  file: 
    path: "{{ lookup('env','MT_DISK') }}/textures/server"
    state: directory
    owner: minetest
    group: minetest

- name: Copy texture dir to the default place
  shell: cp -R "{{texture_dir| json_query('files[0].path').split(' ').join('\\ ')}}/*" "{{ lookup('env','MT_DISK') }}/textures/server"
  notify: "Restart Minetest Service"
