#
# texture.yml - Define the texture that is to be loaded on your server
#
# 2020-02-21 created by selfscrum 
# 
---

- name: Create textures Directory
  file: 
    path: "{{ lookup('env','MT_DISK') }}/textures/downloads"
    state: directory
    owner: minetest
    group: minetest

- name: Download Texture path from ContentDB
  uri: 
    url: "https://content.minetest.net/packages/drummyfish/drummyfish/download"
    dest: /tmp/redirect
    status_code: 300
  register: texture_asset

- name: Download redirected file
  get_url: 
    url: "{{ texture_asset.location }}"
    dest: "{{ lookup('env','MT_DISK') }}/textures/downloads/texture.zip"

- name: Unzip the Download
  unarchive:
    src: "{{ lookup('env','MT_DISK') }}/textures/downloads/texture.zip"
    dest: "{{ lookup('env','MT_DISK') }}/textures/downloads"
    owner: minetest
    group: minetest
    remote_src: true

- name: Move the Package
  find: 
    path: "{{ lookup('env','MT_DISK') }}/textures/downloads"
    file_type: directory
  register: texture_dir


- debug: 
    msg: "{{texture_dir}}.files[0].path"
