  
- name: Download mapserver binary from github
  get_url: 
    url: "https://github.com/minetest-mapserver/mapserver/releases/download/{{lookup('env','MT_MPS_VERSION')}}/{{lookup('env','MT_MPS_PLATFORM')}}"
    dest: "{{ lookup('env','MT_DISK') }}/data/mapserver"
    mode: "0750"
    owner: minetest
    group: minetest

# wg0 must be already in operation for this!
- name: Open Firewall for vpn members. 
  become: yes
  command: ufw allow in on wg0 to any port 8080 proto tcp
  ignore_errors: yes

- name: Copy unit file
  become: yes
  template:
    src: mapserver.service.j2
    dest: /etc/systemd/system/mapserver.service
    mode: 0644
  notify: "Restart Mapserver Service"
