- name: Create mods Directory
  file: 
    path: "{{ lookup('env','MT_DISK') }}/mods"
    state: directory
    owner: minetest
    group: minetest

- name: Install inventory Mod
  import_tasks: github_mod.yml
  vars:
    module: unified_inventory
    module_path: minetest-mods/unified_inventory